name: C/C++ CI

on:
  push:
    branches: [ "demo5" ]
  pull_request:
    branches: [ "demo5" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        cd app/consapp/
        make all

